--Version: 1.0

client_script {
    'client/main.lua',
    '@es_extended/locale.lua',
	'config.lua',
	'locales/de.lua',
	'locales/br.lua',
	'locales/en.lua',
	'locales/fi.lua',
	'locales/fr.lua',
	'locales/es.lua',
	'locales/sv.lua',
	'locales/pl.lua',
	'locales/cs.lua',
    'config.lua'
}

server_script 'server/main.lua'

ui_page "html/jobui.html"

files {
    'html/jobui.html',
    'html/jobjs.js',
    'html/css/animate.min.css',
    'html/css/bootstrap.min.css',
    'html/css/flaticon.css',
    'html/css/font-awesome.min.css',
    'html/css/gijgo.css',
    'html/css/jquery-ui.css',
    'html/css/magnific-popup.css',
    'html/css/nice-select.css',
    'html/css/owl.carousel.min.css',
    'html/css/slicknav.css',
    'html/css/style.css',
    'html/css/themify-icons.css',
    'html/css/themify-icons.css',
    'html/fonts/Flaticon.eot',
    'html/fonts/Flaticon.svg',
    'html/fonts/Flaticon.ttf',
    'html/fonts/Flaticon.woff',
    'html/fonts/Flaticon.woff2',
    'html/fonts/Flaticond41d.eot',
    'html/fonts/fontawesome-webfont3e6e.eot',
    'html/fonts/fontawesome-webfont3e6e.svg',
    'html/fonts/fontawesome-webfont3e6e.ttf',
    'html/fonts/fontawesome-webfont3e6e.woff',
    'html/fonts/fontawesome-webfont3e6e.woff2',
    'html/fonts/fontawesome-webfontd41d.eot',
    'html/fonts/gijgo-materialba15.eot',
    'html/fonts/gijgo-materialba15.svg',
    'html/fonts/gijgo-materialba15.ttf',
    'html/fonts/gijgo-materialba15.woff',
    'html/fonts/themify9f24.eot',
    'html/fonts/themify9f24.svg',
    'html/fonts/themify9f24.ttf',
    'html/fonts/themify9f24.woff',
    'html/fonts/themifyd41d.eot',
    'html/img/banner/banner.png',
    'html/img/banner/bradcam.png',
    'html/img/banner/illustration.png',
    'html/img/svg_icon/1.svg',
    'html/img/svg_icon/2.svg',
    'html/img/svg_icon/chomeur.svg',
    'html/img/logo.png',
    'html/js/ajax-form.js',
    'html/js/bootstrap.min.js',
    'html/js/contact.js',
    'html/js/gijgo.min.js',
    'html/js/imagesloaded.pkgd.min.js',
    'html/js/isotope.pkgd.min.js',
    'html/js/jquery.ajaxchimp.min.js',
    'html/js/jquery.counterup.min.js',
    'html/js/jquery.form.js',
    'html/js/jquery.magnific-popup.min.js',
    'html/js/jquery.scrollUp.min.js',
    'html/js/jquery.slicknav.min.js',
    'html/js/jquery.validate.min.js',
    'html/js/mail-script.js',
    'html/js/main.js',
    'html/js/nice-select.min.js',
    'html/js/owl.carousel.min.js',
    'html/js/plugins.js',
    'html/js/popper.min.js',
    'html/js/range.js',
    'html/js/scrollIt.js',
    'html/js/waypoints.min.js',
    'html/js/wow.min.js',
    'html/js/vendor/jquery-1.12.4.min.js',
    'html/js/vendor/modernizr-3.5.0.min.js'
}